# Generated by Django 4.2.4 on 2023-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_cod_product_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
